In [1]:
print("hello")

hello

In [2]:
import pandas as pd

txt_file = "Ticket Data.txt"

df = pd.read_csv(txt_file)

In [ ]:
df.head()

,ORDER_NUMBER,ORDER_ID,ORDER_UNIT_ID,ACCEPTANCE_TIME,COMPLETION_TIME,CUSTOMER_NUMBER,CUSTOMER_COUNT,ORDER_TYPE,ORDER_CLASS,PROCESSING_STATUS,...,PROCESSING_END_TIME_MINIMUM,ACCEPTANCE_TIME_MINIMUM,ASSIGNMENT_TIME_MINIMUM,IMIL_TIME_MINIMUM,CUSTOMER_TIME_MINIMUM,START_TIME_MINIMUM,ASSIGNMENT_TIME,ASSIGNED_BY_NAME,ASSIGNMENT_PROCESSING_STATUS,ASSIGNMENT_ADDITIONAL_INFO
0,001-0671177/24,114680574,NaN,11/05/2024 11:00,11/05/2024 11:30,123,3,Short Ticket,SK,Completed,...,11/05/2024 11:00,11/05/2024 11:00,NaN,NaN,11/05/2024 11:00,NaN,NaN,NaN,NaN,NaN
1,001-0682295/24,114691514,NaN,11/05/2024 13:00,11/05/2024 13:45,123,3,Short Ticket,SK,Completed,...,11/05/2024 13:00,11/05/2024 13:00,NaN,NaN,11/05/2024 13:00,NaN,NaN,NaN,NaN,NaN
2,001-0670952/24,114680352,NaN,11/06/2024 08:00,11/06/2024 08:30,123,3,Short Ticket,SK,Completed,...,11/06/2024 08:00,11/06/2024 08:00,NaN,NaN,11/06/2024 08:00,NaN,NaN,NaN,NaN,NaN
3,001-0671369/24,114680756,NaN,11/06/2024 10:00,11/06/2024 10:15,123,3,Short Ticket,SK,Completed,...,11/06/2024 10:00,11/06/2024 10:00,NaN,NaN,11/06/2024 10:00,NaN,NaN,NaN,NaN,NaN
4,001-0670929/24,114680329,NaN,11/06/2024 12:00,11/06/2024 13:00,123,3,Task,SK,Completed,...,11/06/2024 12:00,11/06/2024 12:00,NaN,NaN,11/06/2024 12:00,NaN,NaN,NaN,NaN,NaN

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42 entries, 0 to 41
Data columns (total 38 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   ORDER_NUMBER                          42 non-null     object
 1   ORDER_ID                              42 non-null     int64
 2   ORDER_UNIT_ID                         0 non-null      float64
 3   ACCEPTANCE_TIME                       42 non-null     object
 4   COMPLETION_TIME                       42 non-null     object
 5   CUSTOMER_NUMBER                       42 non-null     int64
 6   CUSTOMER_COUNT                        42 non-null     int64
 7   ORDER_TYPE                            42 non-null     object
 8   ORDER_CLASS                           42 non-null     object
 9   PROCESSING_STATUS                     42 non-null     object
 10  SERVICE_CATEGORY                      42 non-null     object
 11  ORDER_DESCRIPTION_1                   42 non-null     object
 12  ORDER_DESCRIPTION_2                   42 non-null     object
 13  ORDER_DESCRIPTION_3_MAXIMUM           23 non-null     object
 14  ADDITIONAL_ORDER_DESCRIPTION_MAXIMUM  19 non-null     object
 15  NOTE_MAXIMUM                          42 non-null     object
 16  PLANNING_GROUP_KB                     42 non-null     object
 17  COMPLETION_RESULT_KB                  26 non-null     object
 18  REFERENCE_COMPLETION_RESULT           22 non-null     object
 19  COMPLETION_NOTE_MAXIMUM               42 non-null     object
 20  NETWORK_LEVEL                         42 non-null     object
 21  CAUSE                                 29 non-null     object
 22  REFERENCE_ERROR_CAUSE                 25 non-null     object
 23  SERVICE_PROVIDER                      42 non-null     object
 24  REFERENCE_SERVICE_PROVIDER            23 non-null     object
 25  SUBUNIT_NAME                          19 non-null     object
 26  CUSTOMER_COMPLETION_TIME              42 non-null     object
 27  PROCESSING_END_TIME_MAXIMUM           42 non-null     object
 28  PROCESSING_END_TIME_MINIMUM           42 non-null     object
 29  ACCEPTANCE_TIME_MINIMUM               23 non-null     object
 30  ASSIGNMENT_TIME_MINIMUM               0 non-null      float64
 31  IMIL_TIME_MINIMUM                     19 non-null     object
 32  CUSTOMER_TIME_MINIMUM                 23 non-null     object
 33  START_TIME_MINIMUM                    0 non-null      float64
 34  ASSIGNMENT_TIME                       0 non-null      float64
 35  ASSIGNED_BY_NAME                      0 non-null      float64
 36  ASSIGNMENT_PROCESSING_STATUS          0 non-null      float64
 37  ASSIGNMENT_ADDITIONAL_INFO            0 non-null      float64
dtypes: float64(7), int64(3), object(28)
memory usage: 12.6+ KB

In [7]:
df['SERVICE_CATEGORY'].value_counts()

SERVICE_CATEGORY
HDW     14
SOP      6
NTF      4
NET      3
KAI      3
KAV      3
GIGA     3
VOD      3
KAD      3
Name: count, dtype: int64

In [8]:
df.columns

Index(['ORDER_NUMBER', 'ORDER_ID', 'ORDER_UNIT_ID', 'ACCEPTANCE_TIME',
       'COMPLETION_TIME', 'CUSTOMER_NUMBER', 'CUSTOMER_COUNT', 'ORDER_TYPE',
       'ORDER_CLASS', 'PROCESSING_STATUS', 'SERVICE_CATEGORY',
       'ORDER_DESCRIPTION_1', 'ORDER_DESCRIPTION_2',
       'ORDER_DESCRIPTION_3_MAXIMUM', 'ADDITIONAL_ORDER_DESCRIPTION_MAXIMUM',
       'NOTE_MAXIMUM', 'PLANNING_GROUP_KB', 'COMPLETION_RESULT_KB',
       'REFERENCE_COMPLETION_RESULT', 'COMPLETION_NOTE_MAXIMUM',
       'NETWORK_LEVEL', 'CAUSE', 'REFERENCE_ERROR_CAUSE', 'SERVICE_PROVIDER',
       'REFERENCE_SERVICE_PROVIDER', 'SUBUNIT_NAME',
       'CUSTOMER_COMPLETION_TIME', 'PROCESSING_END_TIME_MAXIMUM',
       'PROCESSING_END_TIME_MINIMUM', 'ACCEPTANCE_TIME_MINIMUM',
       'ASSIGNMENT_TIME_MINIMUM', 'IMIL_TIME_MINIMUM', 'CUSTOMER_TIME_MINIMUM',
       'START_TIME_MINIMUM', 'ASSIGNMENT_TIME', 'ASSIGNED_BY_NAME',
       'ASSIGNMENT_PROCESSING_STATUS', 'ASSIGNMENT_ADDITIONAL_INFO'],
      dtype='object')

In [11]:
pd.set_option('display.max_columns', None)
df.sample(1)

,ORDER_NUMBER,ORDER_ID,ORDER_UNIT_ID,ACCEPTANCE_TIME,COMPLETION_TIME,CUSTOMER_NUMBER,CUSTOMER_COUNT,ORDER_TYPE,ORDER_CLASS,PROCESSING_STATUS,SERVICE_CATEGORY,ORDER_DESCRIPTION_1,ORDER_DESCRIPTION_2,ORDER_DESCRIPTION_3_MAXIMUM,ADDITIONAL_ORDER_DESCRIPTION_MAXIMUM,NOTE_MAXIMUM,PLANNING_GROUP_KB,COMPLETION_RESULT_KB,REFERENCE_COMPLETION_RESULT,COMPLETION_NOTE_MAXIMUM,NETWORK_LEVEL,CAUSE,REFERENCE_ERROR_CAUSE,SERVICE_PROVIDER,REFERENCE_SERVICE_PROVIDER,SUBUNIT_NAME,CUSTOMER_COMPLETION_TIME,PROCESSING_END_TIME_MAXIMUM,PROCESSING_END_TIME_MINIMUM,ACCEPTANCE_TIME_MINIMUM,ASSIGNMENT_TIME_MINIMUM,IMIL_TIME_MINIMUM,CUSTOMER_TIME_MINIMUM,START_TIME_MINIMUM,ASSIGNMENT_TIME,ASSIGNED_BY_NAME,ASSIGNMENT_PROCESSING_STATUS,ASSIGNMENT_ADDITIONAL_INFO
14,001-0671180/24,114680577,NaN,11/10/2024 11:00,11/10/2024 11:30,789,2,Short Ticket,SK,Completed,HDW,Cable Router,WLAN,Stable,NaN,WLAN Stable After Restart,TSCW2,Router Restarted and Stable,NaN,OK,NZ,URS_KIP_WLAN-Settings_Reset,NaN,Customer,Customer,NaN,11/10/2024 11:30,11/10/2024 11:00,11/10/2024 11:00,11/10/2024 11:00,NaN,NaN,11/10/2024 11:00,NaN,NaN,NaN,NaN,NaN

In [12]:
for col in df.columns:
    print(f"Column: {col}")
    print(df[col].value_counts())
    print("\n")

Column: ORDER_NUMBER
ORDER_NUMBER
001-0671177/24    1
001-0682295/24    1
001-0670952/24    1
001-0671369/24    1
001-0670929/24    1
001-0670741/24    1
001-0671178/24    1
001-0682296/24    1
001-0670953/24    1
001-0671370/24    1
001-0670930/24    1
001-0670742/24    1
001-0671179/24    1
001-0682297/24    1
001-0671180/24    1
001-0682298/24    1
001-0670954/24    1
001-0671371/24    1
001-0670931/24    1
001-0670743/24    1
001-0671181/24    1
001-0671182/24    1
001-0682299/24    1
001-0670955/24    1
001-0671372/24    1
001-0670932/24    1
001-0670744/24    1
001-0671183/24    1
001-0682300/24    1
001-0670956/24    1
001-0671373/24    1
001-0670933/24    1
001-0670745/24    1
001-0671184/24    1
001-0682301/24    1
001-0671185/24    1
001-0682302/24    1
001-0670957/24    1
001-0671374/24    1
001-0670934/24    1
001-0670746/24    1
001-0671186/24    1
Name: count, dtype: int64


Column: ORDER_ID
ORDER_ID
114680574    1
114691514    1
114680352    1
114680756    1
114680329    1
114680146    1
114680575    1
114691515    1
114680353    1
114680757    1
114680330    1
114680147    1
114680576    1
114691516    1
114680577    1
114691517    1
114680354    1
114680758    1
114680331    1
114680148    1
114680578    1
114680579    1
114691518    1
114680355    1
114680759    1
114680332    1
114680149    1
114680580    1
114691519    1
114680356    1
114680760    1
114680333    1
114680150    1
114680581    1
114691520    1
114680582    1
114691521    1
114680357    1
114680761    1
114680334    1
114680151    1
114680583    1
Name: count, dtype: int64


Column: ORDER_UNIT_ID
Series([], Name: count, dtype: int64)


Column: ACCEPTANCE_TIME
ACCEPTANCE_TIME
11/16/2024 11:00    2
11/13/2024 12:00    2
11/05/2024 11:00    1
11/05/2024 13:00    1
11/06/2024 12:00    1
11/07/2024 09:00    1
11/06/2024 08:00    1
11/06/2024 10:00    1
11/08/2024 08:00    1
11/07/2024 11:00    1
11/08/2024 14:00    1
11/08/2024 10:00    1
11/09/2024 11:00    1
11/09/2024 13:00    1
11/10/2024 11:00    1
11/08/2024 12:00    1
11/10/2024 13:00    1
11/11/2024 08:00    1
11/11/2024 12:00    1
11/11/2024 10:00    1
11/12/2024 09:00    1
11/12/2024 11:00    1
11/13/2024 10:00    1
11/09/2024 09:00    1
11/14/2024 08:00    1
11/14/2024 10:00    1
11/15/2024 12:00    1
11/15/2024 09:00    1
11/12/2024 08:00    1
11/12/2024 10:00    1
11/13/2024 14:00    1
11/14/2024 09:00    1
11/14/2024 11:00    1
11/15/2024 08:00    1
11/17/2024 13:00    1
11/18/2024 08:00    1
11/18/2024 10:00    1
11/19/2024 12:00    1
11/19/2024 09:00    1
11/20/2024 11:00    1
Name: count, dtype: int64


Column: COMPLETION_TIME
COMPLETION_TIME
11/16/2024 11:30    2
11/05/2024 13:45    1
11/06/2024 08:30    1
11/06/2024 10:15    1
11/06/2024 13:00    1
11/07/2024 09:15    1
11/07/2024 11:30    1
11/08/2024 08:45    1
11/05/2024 11:30    1
11/08/2024 10:30    1
11/08/2024 12:15    1
11/09/2024 09:15    1
11/08/2024 15:00    1
11/09/2024 13:45    1
11/10/2024 11:30    1
11/10/2024 13:45    1
11/09/2024 11:30    1
11/11/2024 10:15    1
11/11/2024 13:00    1
11/12/2024 09:15    1
11/12/2024 11:30    1
11/13/2024 10:30    1
11/13/2024 12:45    1
11/14/2024 08:30    1
11/11/2024 08:30    1
11/14/2024 10:15    1
11/15/2024 13:00    1
11/15/2024 09:15    1
11/12/2024 08:45    1
11/12/2024 10:30    1
11/13/2024 12:15    1
11/13/2024 15:00    1
11/14/2024 09:15    1
11/14/2024 11:30    1
11/15/2024 08:45    1
11/17/2024 13:45    1
11/18/2024 08:30    1
11/18/2024 10:15    1
11/19/2024 13:00    1
11/19/2024 09:15    1
11/20/2024 11:30    1
Name: count, dtype: int64


Column: CUSTOMER_NUMBER
CUSTOMER_NUMBER
123    14
456    14
789    14
Name: count, dtype: int64


Column: CUSTOMER_COUNT
CUSTOMER_COUNT
3    14
4    14
2    14
Name: count, dtype: int64


Column: ORDER_TYPE
ORDER_TYPE
Short Ticket    30
Kurzticket       6
Task             5
Aufgabe          1
Name: count, dtype: int64


Column: ORDER_CLASS
ORDER_CLASS
SK    42
Name: count, dtype: int64


Column: PROCESSING_STATUS
PROCESSING_STATUS
Completed    35
ab            7
Name: count, dtype: int64


Column: SERVICE_CATEGORY
SERVICE_CATEGORY
HDW     14
SOP      6
NTF      4
NET      3
KAI      3
KAV      3
GIGA     3
VOD      3
KAD      3
Name: count, dtype: int64


Column: ORDER_DESCRIPTION_1
ORDER_DESCRIPTION_1
Cable Router                                     13
Activation VKD-Modem (Third-Party Modem User)     4
Inquiry - KIP                                     3
Internet                                          3
Gigabit Option                                    3
HD Channel                                        2
Smartcard                                         2
Video on Demand                                   2
Activation VKD Modem (Third-Party Modem User)     2
Sender                                            1
CI-Modul                                          1
Kabelrouter                                       1
Request - KIP                                     1
Kundenportal                                      1
Movies                                            1
Password                                          1
Customer Portal                                   1
Name: count, dtype: int64


Column: ORDER_DESCRIPTION_2
ORDER_DESCRIPTION_2
WLAN                          10
Cable Modem / Cable Router     6
Contract                       3
Internet                       3
kein Zugriff                   2
kein Empfang                   2
langsam                        1
Invoice                        1
Aktivierung fehlgeschlagen     1
Slow                           1
Not Recognized                 1
Blurred                        1
Not Booked                     1
Stuttering                     1
Forgotten                      1
No Internet                    1
Connection Unstable            1
No Access                      1
Artifacts                      1
Activation Delayed             1
Error Message                  1
Invoice Problem                1
Name: count, dtype: int64


Column: ORDER_DESCRIPTION_3_MAXIMUM
ORDER_DESCRIPTION_3_MAXIMUM
No Connection                             4
Preliminary Result See Remarks Field      4
Slow                                      3
No connection                             2
Stable                                    2
Preliminary test result see note field    2
Unstable                                  1
Installation process/date                 1
Invoice Clarification                     1
Tariff Change                             1
Relocation                                1
keine Verbindung                          1
Name: count, dtype: int64


Column: ADDITIONAL_ORDER_DESCRIPTION_MAXIMUM
ADDITIONAL_ORDER_DESCRIPTION_MAXIMUM
Downloadgeschwindigkeit gering      1
CI-Modul defekt                     1
Bestimmte Sender fehlen             1
Gigabit Option nicht aktivierbar    1
Filme laden nicht                   1
Passwort vergessen                  1
Upload Too Slow                     1
Smartcard Not Recognized            1
Poor Picture Quality                1
Customer Wants Gigabit              1
Movies Stutter                      1
Password Forgotten                  1
Router Defective                    1
Connection Keeps Dropping           1
Smartcard Not Working               1
Picture Interference                1
Confirmation Missing                1
Playback Not Possible               1
Invoice Not Displayed               1
Name: count, dtype: int64


Column: NOTE_MAXIMUM
NOTE_MAXIMUM
TSCW2                        10
TSCS2                         6
TSCKT                         3
Activation Problem            2
WLAN No Connection            2
Modem Activation              2
WLAN slow                     1
WLAN no connection            1
Modem activation              1
Activation problem            1
WLAN unstable                 1
No internet connection        1
Installation request          1
WLAN Stable                   1
Invoice Inquiry               1
WLAN Stable After Restart     1
Tariff Change Request         1
Internet Slow                 1
Relocation Request            1
Router startet nicht          1
WLAN Slow                     1
Internet No Connection        1
Router Defective              1
Name: count, dtype: int64


Column: PLANNING_GROUP_KB
PLANNING_GROUP_KB
TSCW2                         12
TSCS2                          6
TSCKT                          5
SIT12                          3
TITAN Successful               2
Neues CI-Modul bestellt        1
Bandbreite erhöht              1
TITAN erfolgreich              1
Passwort zurückgesetzt         1
Line Checked                   1
Sendeanlage geprüft            1
Smartcard Replaced             1
Bandwidth Checked              1
Password Reset                 1
Technician Commissioned        1
Connection Optimization        1
PIN Forgotten                  1
Technician Checking Signal     1
Technical Problem Found        1
Name: count, dtype: int64


Column: COMPLETION_RESULT_KB
COMPLETION_RESULT_KB
SIT12                               3
WLAN settings optimized             1
Router restarted                    1
Technician appointment scheduled    1
Channel changed                     1
TITAN Session Aborted               1
Router reset                        1
Forwarded to Accounting             1
Firmware Update Performed           1
Channel Change Automatic            1
TITAN Successful                    1
Router Replaced                     1
Order Created for Tariff Change     1
Router Restarted and Stable         1
Relocation Order Created            1
Troubleshooting Commissioned        1
Frequency Band Changed              1
TITAN Rejected                      1
Technician Ordered                  1
Austauschgerät versendet            1
Ticket an Technik weitergeleitet    1
New Router Sent                     1
Signal Strength Increased           1
Customer Service Contacted          1
Name: count, dtype: int64


Column: REFERENCE_COMPLETION_RESULT
REFERENCE_COMPLETION_RESULT
OK                               16
TSC#KCC                           3
New BI order created              1
Activation Performed Manually     1
Technician on Site                1
Name: count, dtype: int64


Column: COMPLETION_NOTE_MAXIMUM
COMPLETION_NOTE_MAXIMUM
OK         19
NZ         19
TSC#KCC     3
Error       1
Name: count, dtype: int64


Column: NETWORK_LEVEL
NETWORK_LEVEL
NZ                                 23
SIT11                               3
k03                                 3
CM_BERA_KD_Bandbreite               1
BM_STOE_KAV_Sender_Fehlen           1
URS_KIP_CI_Modul_Defekt             1
URS_KIP_Kundenportal                1
URS_KIP_BandwidthProblems           1
BM_STOE_KAI_Smartcard_Defect        1
URS_KIP_VideoOnDemandProblems       1
CM_BERA_KD_Password                 1
URS_KIP_Defective_Device            1
CM_BERA_KD_ConnectionProblems       1
URS_KIP_SmartcardProblems           1
BM_STOE_KAV_PictureInterference     1
URS_KIP_CustomerPortalProblems      1
Name: count, dtype: int64


Column: CAUSE
CAUSE
URS_KIP_WLAN-Settings_Reset                              3
k03                                                      3
SIT11                                                    3
CM_BERA_KD_Contract                                      2
URS_KIP_No_Connection                                    2
URS_KIP_Reset_WLAN_Settings                              2
BM_STOE_HDW_FunktSt_KIP_WLAN_ohne_Funkt_nicht            2
CM_BERA_KD_Complaint_about_BI_Installation               1
BM_STOE_HDW_Malfunction_KIP_WLAN_Without_Function_Not    1
CM_BERA_KD_Invoice                                       1
URS_KIP_Slow_Connection                                  1
URS_KIP_Defektes_Geraet                                  1
Techniker behebt Fehler                                  1
Zugriffsproblem behoben                                  1
CM_BERA_KD_HardwareDefect                                1
Problem Solved                                           1
Gigabit Option Activated                                 1
Customer Informed                                        1
Problem Identified                                       1
Name: count, dtype: int64


Column: REFERENCE_ERROR_CAUSE
REFERENCE_ERROR_CAUSE
Customer                                     11
Kunde                                         5
KD                                            3
BI order closed                               1
Troubleshooting - Customer reported issue     1
Activation Successful                         1
Modem Activated                               1
Technician Solved Problem                     1
Incorrect Data                                1
Name: count, dtype: int64


Column: SERVICE_PROVIDER
SERVICE_PROVIDER
Customer        30
Kunde            6
KD               3
End Customer     2
Endkunde         1
Name: count, dtype: int64


Column: REFERENCE_SERVICE_PROVIDER
REFERENCE_SERVICE_PROVIDER
Customer        19
End Customer     3
Kunde            1
Name: count, dtype: int64


Column: SUBUNIT_NAME
SUBUNIT_NAME
11/16/2024 11:30    2
11/13/2024 12:45    1
11/14/2024 08:30    1
11/14/2024 10:15    1
11/15/2024 13:00    1
11/15/2024 09:15    1
11/12/2024 10:30    1
11/13/2024 12:15    1
11/13/2024 15:00    1
11/14/2024 09:15    1
11/14/2024 11:30    1
11/15/2024 08:45    1
11/17/2024 13:45    1
11/18/2024 08:30    1
11/18/2024 10:15    1
11/19/2024 13:00    1
11/19/2024 09:15    1
11/20/2024 11:30    1
Name: count, dtype: int64


Column: CUSTOMER_COMPLETION_TIME
CUSTOMER_COMPLETION_TIME
11/16/2024 11:00    2
11/13/2024 12:00    2
11/05/2024 11:30    1
11/05/2024 13:45    1
11/06/2024 13:00    1
11/07/2024 09:15    1
11/06/2024 08:30    1
11/06/2024 10:15    1
11/08/2024 08:45    1
11/07/2024 11:30    1
11/08/2024 15:00    1
11/08/2024 10:30    1
11/09/2024 11:30    1
11/09/2024 13:45    1
11/10/2024 11:30    1
11/08/2024 12:15    1
11/10/2024 13:45    1
11/11/2024 08:30    1
11/11/2024 13:00    1
11/11/2024 10:15    1
11/12/2024 09:15    1
11/12/2024 11:30    1
11/13/2024 10:30    1
11/09/2024 09:15    1
11/14/2024 08:00    1
11/14/2024 10:00    1
11/15/2024 12:00    1
11/15/2024 09:00    1
11/12/2024 08:45    1
11/12/2024 10:00    1
11/13/2024 14:00    1
11/14/2024 09:00    1
11/14/2024 11:00    1
11/15/2024 08:00    1
11/17/2024 13:00    1
11/18/2024 08:00    1
11/18/2024 10:00    1
11/19/2024 12:00    1
11/19/2024 09:00    1
11/20/2024 11:00    1
Name: count, dtype: int64


Column: PROCESSING_END_TIME_MAXIMUM
PROCESSING_END_TIME_MAXIMUM
11/16/2024 11:00    2
11/13/2024 12:00    2
11/05/2024 11:00    1
11/05/2024 13:00    1
11/06/2024 12:00    1
11/07/2024 09:00    1
11/06/2024 08:00    1
11/06/2024 10:00    1
11/08/2024 08:00    1
11/07/2024 11:00    1
11/08/2024 14:00    1
11/08/2024 10:00    1
11/09/2024 11:00    1
11/09/2024 13:00    1
11/10/2024 11:00    1
11/08/2024 12:00    1
11/10/2024 13:00    1
11/11/2024 08:00    1
11/11/2024 12:00    1
11/11/2024 10:00    1
11/12/2024 09:00    1
11/12/2024 11:00    1
11/13/2024 10:00    1
11/09/2024 09:00    1
11/14/2024 08:00    1
11/14/2024 10:00    1
11/15/2024 12:00    1
11/15/2024 09:00    1
11/12/2024 08:00    1
11/12/2024 10:00    1
11/13/2024 14:00    1
11/14/2024 09:00    1
11/14/2024 11:00    1
11/15/2024 08:00    1
11/17/2024 13:00    1
11/18/2024 08:00    1
11/18/2024 10:00    1
11/19/2024 12:00    1
11/19/2024 09:00    1
11/20/2024 11:00    1
Name: count, dtype: int64


Column: PROCESSING_END_TIME_MINIMUM
PROCESSING_END_TIME_MINIMUM
11/16/2024 11:00    2
11/13/2024 12:00    2
11/05/2024 11:00    1
11/05/2024 13:00    1
11/06/2024 12:00    1
11/07/2024 09:00    1
11/06/2024 08:00    1
11/06/2024 10:00    1
11/08/2024 08:00    1
11/07/2024 11:00    1
11/08/2024 14:00    1
11/08/2024 10:00    1
11/09/2024 11:00    1
11/09/2024 13:00    1
11/10/2024 11:00    1
11/08/2024 12:00    1
11/10/2024 13:00    1
11/11/2024 08:00    1
11/11/2024 12:00    1
11/11/2024 10:00    1
11/12/2024 09:00    1
11/12/2024 11:00    1
11/13/2024 10:00    1
11/09/2024 09:00    1
11/14/2024 08:00    1
11/14/2024 10:00    1
11/15/2024 12:00    1
11/15/2024 09:00    1
11/12/2024 08:00    1
11/12/2024 10:00    1
11/13/2024 14:00    1
11/14/2024 09:00    1
11/14/2024 11:00    1
11/15/2024 08:00    1
11/17/2024 13:00    1
11/18/2024 08:00    1
11/18/2024 10:00    1
11/19/2024 12:00    1
11/19/2024 09:00    1
11/20/2024 11:00    1
Name: count, dtype: int64


Column: ACCEPTANCE_TIME_MINIMUM
ACCEPTANCE_TIME_MINIMUM
11/05/2024 11:00    1
11/05/2024 13:00    1
11/06/2024 08:00    1
11/06/2024 10:00    1
11/06/2024 12:00    1
11/07/2024 09:00    1
11/07/2024 11:00    1
11/08/2024 08:00    1
11/08/2024 10:00    1
11/08/2024 12:00    1
11/08/2024 14:00    1
11/09/2024 09:00    1
11/09/2024 11:00    1
11/09/2024 13:00    1
11/10/2024 11:00    1
11/10/2024 13:00    1
11/11/2024 08:00    1
11/11/2024 10:00    1
11/11/2024 12:00    1
11/12/2024 09:00    1
11/12/2024 11:00    1
11/13/2024 10:00    1
11/12/2024 08:00    1
Name: count, dtype: int64


Column: ASSIGNMENT_TIME_MINIMUM
Series([], Name: count, dtype: int64)


Column: IMIL_TIME_MINIMUM
IMIL_TIME_MINIMUM
11/13/2024 12:00    2
11/16/2024 11:00    2
11/14/2024 08:00    1
11/15/2024 12:00    1
11/14/2024 10:00    1
11/15/2024 09:00    1
11/12/2024 10:00    1
11/13/2024 14:00    1
11/14/2024 09:00    1
11/14/2024 11:00    1
11/15/2024 08:00    1
11/17/2024 13:00    1
11/18/2024 08:00    1
11/18/2024 10:00    1
11/19/2024 12:00    1
11/19/2024 09:00    1
11/20/2024 11:00    1
Name: count, dtype: int64


Column: CUSTOMER_TIME_MINIMUM
CUSTOMER_TIME_MINIMUM
11/05/2024 11:00    1
11/05/2024 13:00    1
11/06/2024 08:00    1
11/06/2024 10:00    1
11/06/2024 12:00    1
11/07/2024 09:00    1
11/07/2024 11:00    1
11/08/2024 08:00    1
11/08/2024 10:00    1
11/08/2024 12:00    1
11/08/2024 14:00    1
11/09/2024 09:00    1
11/09/2024 11:00    1
11/09/2024 13:00    1
11/10/2024 11:00    1
11/10/2024 13:00    1
11/11/2024 08:00    1
11/11/2024 10:00    1
11/11/2024 12:00    1
11/12/2024 09:00    1
11/12/2024 11:00    1
11/13/2024 10:00    1
11/12/2024 08:00    1
Name: count, dtype: int64


Column: START_TIME_MINIMUM
Series([], Name: count, dtype: int64)


Column: ASSIGNMENT_TIME
Series([], Name: count, dtype: int64)


Column: ASSIGNED_BY_NAME
Series([], Name: count, dtype: int64)


Column: ASSIGNMENT_PROCESSING_STATUS
Series([], Name: count, dtype: int64)


Column: ASSIGNMENT_ADDITIONAL_INFO
Series([], Name: count, dtype: int64)

In [13]:
df['CUSTOMER_NUMBER'].value_counts()

CUSTOMER_NUMBER
123    14
456    14
789    14
Name: count, dtype: int64

In [16]:
df[df['CUSTOMER_NUMBER'] == 123].sort_values('ACCEPTANCE_TIME')

,ORDER_NUMBER,ORDER_ID,ORDER_UNIT_ID,ACCEPTANCE_TIME,COMPLETION_TIME,CUSTOMER_NUMBER,CUSTOMER_COUNT,ORDER_TYPE,ORDER_CLASS,PROCESSING_STATUS,SERVICE_CATEGORY,ORDER_DESCRIPTION_1,ORDER_DESCRIPTION_2,ORDER_DESCRIPTION_3_MAXIMUM,ADDITIONAL_ORDER_DESCRIPTION_MAXIMUM,NOTE_MAXIMUM,PLANNING_GROUP_KB,COMPLETION_RESULT_KB,REFERENCE_COMPLETION_RESULT,COMPLETION_NOTE_MAXIMUM,NETWORK_LEVEL,CAUSE,REFERENCE_ERROR_CAUSE,SERVICE_PROVIDER,REFERENCE_SERVICE_PROVIDER,SUBUNIT_NAME,CUSTOMER_COMPLETION_TIME,PROCESSING_END_TIME_MAXIMUM,PROCESSING_END_TIME_MINIMUM,ACCEPTANCE_TIME_MINIMUM,ASSIGNMENT_TIME_MINIMUM,IMIL_TIME_MINIMUM,CUSTOMER_TIME_MINIMUM,START_TIME_MINIMUM,ASSIGNMENT_TIME,ASSIGNED_BY_NAME,ASSIGNMENT_PROCESSING_STATUS,ASSIGNMENT_ADDITIONAL_INFO
0,001-0671177/24,114680574,NaN,11/05/2024 11:00,11/05/2024 11:30,123,3,Short Ticket,SK,Completed,HDW,Cable Router,WLAN,Slow,NaN,WLAN slow,TSCW2,WLAN settings optimized,NaN,OK,NZ,URS_KIP_Reset_WLAN_Settings,NaN,Customer,Customer,NaN,11/05/2024 11:30,11/05/2024 11:00,11/05/2024 11:00,11/05/2024 11:00,NaN,NaN,11/05/2024 11:00,NaN,NaN,NaN,NaN,NaN
1,001-0682295/24,114691514,NaN,11/05/2024 13:00,11/05/2024 13:45,123,3,Short Ticket,SK,Completed,NTF,Request - KIP,Contract,Installation process/date,NaN,Installation request,TSCKT,Technician appointment scheduled,NaN,OK,NZ,CM_BERA_KD_Complaint_about_BI_Installation,NaN,Customer,Customer,NaN,11/05/2024 13:45,11/05/2024 13:00,11/05/2024 13:00,11/05/2024 13:00,NaN,NaN,11/05/2024 13:00,NaN,NaN,NaN,NaN,NaN
2,001-0670952/24,114680352,NaN,11/06/2024 08:00,11/06/2024 08:30,123,3,Short Ticket,SK,Completed,HDW,Cable Router,Internet,No connection,NaN,No internet connection,TSCW2,Router restarted,NaN,OK,NZ,URS_KIP_No_Connection,NaN,Customer,Customer,NaN,11/06/2024 08:30,11/06/2024 08:00,11/06/2024 08:00,11/06/2024 08:00,NaN,NaN,11/06/2024 08:00,NaN,NaN,NaN,NaN,NaN
3,001-0671369/24,114680756,NaN,11/06/2024 10:00,11/06/2024 10:15,123,3,Short Ticket,SK,Completed,HDW,Cable Router,WLAN,Unstable,NaN,WLAN unstable,TSCW2,Channel changed,NaN,OK,NZ,BM_STOE_HDW_Malfunction_KIP_WLAN_Without_Funct...,NaN,Customer,Customer,NaN,11/06/2024 10:15,11/06/2024 10:00,11/06/2024 10:00,11/06/2024 10:00,NaN,NaN,11/06/2024 10:00,NaN,NaN,NaN,NaN,NaN
4,001-0670929/24,114680329,NaN,11/06/2024 12:00,11/06/2024 13:00,123,3,Task,SK,Completed,SOP,Activation VKD Modem (Third-Party Modem User),Cable Modem / Cable Router,Preliminary test result see note field,NaN,Activation problem,TSCS2,SIT12,New BI order created,TSC#KCC,NZ,SIT11,BI order closed,KD,End Customer,NaN,11/06/2024 13:00,11/06/2024 12:00,11/06/2024 12:00,11/06/2024 12:00,NaN,NaN,11/06/2024 12:00,NaN,NaN,NaN,NaN,NaN
5,001-0670741/24,114680146,NaN,11/07/2024 09:00,11/07/2024 09:15,123,3,Short Ticket,SK,Completed,SOP,Activation VKD Modem (Third-Party Modem User),Cable Modem / Cable Router,Preliminary test result see note field,NaN,Modem activation,TSCS2,TITAN Session Aborted,NaN,OK,NZ,k03,Troubleshooting - Customer reported issue,Customer,Customer,NaN,11/07/2024 09:15,11/07/2024 09:00,11/07/2024 09:00,11/07/2024 09:00,NaN,NaN,11/07/2024 09:00,NaN,NaN,NaN,NaN,NaN
6,001-0671178/24,114680575,NaN,11/07/2024 11:00,11/07/2024 11:30,123,3,Short Ticket,SK,Completed,HDW,Cable Router,WLAN,No connection,NaN,WLAN no connection,TSCW2,Router reset,NaN,OK,NZ,URS_KIP_Reset_WLAN_Settings,NaN,Customer,Customer,NaN,11/07/2024 11:30,11/07/2024 11:00,11/07/2024 11:00,11/07/2024 11:00,NaN,NaN,11/07/2024 11:00,NaN,NaN,NaN,NaN,NaN
21,001-0671182/24,114680579,NaN,11/13/2024 10:00,11/13/2024 10:30,123,3,Kurzticket,SK,ab,HDW,Kabelrouter,WLAN,keine Verbindung,NaN,Router startet nicht,TSCW2,Austauschgerät versendet,NaN,OK,NZ,URS_KIP_Defektes_Geraet,NaN,Kunde,Kunde,NaN,11/13/2024 10:30,11/13/2024 10:00,11/13/2024 10:00,11/13/2024 10:00,NaN,NaN,11/13/2024 10:00,NaN,NaN,NaN,NaN,NaN
22,001-0682299/24,114691518,NaN,11/13/2024 12:00,11/13/2024 12:45,123,3,Kurzticket,SK,ab,NET,Internet,langsam,NaN,Downloadgeschwindigkeit gering,TSCKT,Bandbreite erhöht,NaN,OK,NZ,CM_BERA_KD_Bandbreite,NaN,Kunde,Kunde,NaN,11/13/2024 12:45,11/13/2024 12:00,11/13/2024 12:00,11/13/2024 12:00,NaN,NaN,11/13/2024 12:00,NaN,NaN,NaN,NaN,NaN,NaN
23,001-0670955/24,114680355,NaN,11/14/2024 08:00,11/14/2024 08:30,123,3,Kurzticket,SK,ab,KAI,CI-Modul,kein Empfang,NaN,CI-Modul defekt,TSCW2,Neues CI-Modul bestellt,NaN,OK,NZ,URS_KIP_CI_Modul_Defekt,NaN,Kunde,Kunde,NaN,11/14/2024 08:30,11/14/2024 08:00,11/14/2024 08:00,11/14/2024 08:00,NaN,NaN,11/14/2024 08:00,NaN,NaN,NaN,NaN,NaN,NaN
24,001-0671372/24,114680759,NaN,11/14/2024 10:00,11/14/2024 10:15,123,3,Kurzticket,SK,ab,KAV,Sender,kein Empfang,NaN,Bestimmte Sender fehlen,TSCW2,Sendeanlage geprüft,NaN,OK,NZ,BM_STOE_KAV_Sender_Fehlen,NaN,Kunde,Kunde,NaN,11/14/2024 10:15,11/14/2024 10:00,11/14/2024 10:00,11/14/2024 10:00,NaN,NaN,11/14/2024 10:00,NaN,NaN,NaN,NaN,NaN,NaN
26,001-0670744/24,114680149,NaN,11/15/2024 09:00,11/15/2024 09:15,123,3,Kurzticket,SK,ab,VOD,Video on Demand,kein Zugriff,NaN,Filme laden nicht,TSCS2,TITAN erfolgreich,NaN,OK,NZ,k03,Zugriffsproblem behoben,Kunde,Kunde,NaN,11/15/2024 09:15,11/15/2024 09:00,11/15/2024 09:00,11/15/2024 09:00,NaN,NaN,11/15/2024 09:00,NaN,NaN,NaN,NaN,NaN,NaN
25,001-0670932/24,114680332,NaN,11/15/2024 12:00,11/15/2024 13:00,123,3,Aufgabe,SK,ab,GIGA,Gigabit Option,Aktivierung fehlgeschlagen,NaN,Gigabit Option nicht aktivierbar,TSCS2,SIT12,Ticket an Technik weitergeleitet,TSC#KCC,NZ,SIT11,Techniker behebt Fehler,KD,Endkunde,NaN,11/15/2024 13:00,11/15/2024 12:00,11/15/2024 12:00,11/15/2024 12:00,NaN,NaN,11/15/2024 12:00,NaN,NaN,NaN,NaN,NaN,NaN
27,001-0671183/24,114680580,NaN,11/16/2024 11:00,11/16/2024 11:30,123,3,Kurzticket,SK,ab,KAD,Kundenportal,kein Zugriff,NaN,Passwort vergessen,TSCW2,Passwort zurückgesetzt,NaN,OK,NZ,URS_KIP_Kundenportal,NaN,Kunde,Kunde,NaN,11/16/2024 11:30,11/16/2024 11:00,11/16/2024 11:00,11/16/2024 11:00,NaN,NaN,11/16/2024 11:00,NaN,NaN,NaN,NaN,NaN,NaN

*Note Data is mixing between Germany and English*

In [24]:
df[(df['SERVICE_CATEGORY']=='GIGA' )].sort_values('ACCEPTANCE_TIME')

,ORDER_NUMBER,ORDER_ID,ORDER_UNIT_ID,ACCEPTANCE_TIME,COMPLETION_TIME,CUSTOMER_NUMBER,CUSTOMER_COUNT,ORDER_TYPE,ORDER_CLASS,PROCESSING_STATUS,SERVICE_CATEGORY,ORDER_DESCRIPTION_1,ORDER_DESCRIPTION_2,ORDER_DESCRIPTION_3_MAXIMUM,ADDITIONAL_ORDER_DESCRIPTION_MAXIMUM,NOTE_MAXIMUM,PLANNING_GROUP_KB,COMPLETION_RESULT_KB,REFERENCE_COMPLETION_RESULT,COMPLETION_NOTE_MAXIMUM,NETWORK_LEVEL,CAUSE,REFERENCE_ERROR_CAUSE,SERVICE_PROVIDER,REFERENCE_SERVICE_PROVIDER,SUBUNIT_NAME,CUSTOMER_COMPLETION_TIME,PROCESSING_END_TIME_MAXIMUM,PROCESSING_END_TIME_MINIMUM,ACCEPTANCE_TIME_MINIMUM,ASSIGNMENT_TIME_MINIMUM,IMIL_TIME_MINIMUM,CUSTOMER_TIME_MINIMUM,START_TIME_MINIMUM,ASSIGNMENT_TIME,ASSIGNED_BY_NAME,ASSIGNMENT_PROCESSING_STATUS,ASSIGNMENT_ADDITIONAL_INFO
32,001-0670745/24,114680150,NaN,11/14/2024 09:00,11/14/2024 09:15,456,4,Short Ticket,SK,Completed,GIGA,Gigabit Option,Not Booked,NaN,Customer Wants Gigabit,TSCS2,TITAN Successful,NaN,OK,NZ,k03,Gigabit Option Activated,Customer,Customer,NaN,11/14/2024 09:15,11/14/2024 09:00,11/14/2024 09:00,11/14/2024 09:00,NaN,NaN,11/14/2024 09:00,NaN,NaN,NaN,NaN,NaN,NaN
25,001-0670932/24,114680332,NaN,11/15/2024 12:00,11/15/2024 13:00,123,3,Aufgabe,SK,ab,GIGA,Gigabit Option,Aktivierung fehlgeschlagen,NaN,Gigabit Option nicht aktivierbar,TSCS2,SIT12,Ticket an Technik weitergeleitet,TSC#KCC,NZ,SIT11,Techniker behebt Fehler,KD,Endkunde,NaN,11/15/2024 13:00,11/15/2024 12:00,11/15/2024 12:00,11/15/2024 12:00,NaN,NaN,11/15/2024 12:00,NaN,NaN,NaN,NaN,NaN,NaN
39,001-0670934/24,114680334,NaN,11/19/2024 12:00,11/19/2024 13:00,789,2,Task,SK,Completed,GIGA,Gigabit Option,Activation Delayed,NaN,Confirmation Missing,TSCS2,SIT12,Customer Service Contacted,TSC#KCC,NZ,SIT11,Customer Informed,KD,End Customer,NaN,11/19/2024 13:00,11/19/2024 12:00,11/19/2024 12:00,11/19/2024 12:00,NaN,NaN,11/19/2024 12:00,NaN,NaN,NaN,NaN,NaN,NaN